version: '3'

description: >
  EMAIL and HANDLE are used for git and GitLab or GitHub

env:
  EMAIL: "bob@morane.com"
  HANDLE: "bob"

includes:
  wasm-rt: ./tasks/wasm-rt.yml
  golang: ./tasks/golang.yml
  rust: ./tasks/rust.yml
  git: ./tasks/git.yml
  wws: ./tasks/wws.yml
  




